(function(f,n,l){if("object"===typeof l&&"string"!==typeof l.nodeName)n(f,l);else{var p=function(b){for(var e in b)b.hasOwnProperty(e)&&(b[e]=p(b[e]));return Object.freeze(b)};l={};n(f,l);for(var m in l)l.hasOwnProperty(m)&&(Object.getOwnPropertyDescriptor(f,m)||Object.defineProperty(f,m,{get:function(){return p({"1.0.2-dev":l[m]})}}))}})("undefined"===typeof global?this:global,function(f,n){function l(a,c){return a&&(a[c]||(a[c]={}))}function p(a,c){"undefined"!==typeof jasmine&&jasmine?a():"undefined"!==
typeof console&&console&&console.error&&c()}function m(a,c){return c.reduce(function(a,c){return a&&a[c]},a)}var b=b||{};b.scope={};b.inherits=function(a,c){function q(){}q.prototype=c.prototype;a.superClass_=c.prototype;a.prototype=new q;a.prototype.constructor=a;for(var b in c)if("prototype"!=b)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(c,b);d&&Object.defineProperty(a,b,d)}else a[b]=c[b]};b.ASSUME_ES5=!1;b.ASSUME_NO_NATIVE_MAP=!1;b.ASSUME_NO_NATIVE_SET=!1;b.defineProperty=
b.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};b.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};b.global=b.getGlobal(this);b.SYMBOL_PREFIX="jscomp_symbol_";b.initSymbol=function(){b.initSymbol=function(){};b.global.Symbol||(b.global.Symbol=b.Symbol)};b.symbolCounter_=0;b.Symbol=function(a){return b.SYMBOL_PREFIX+(a||"")+b.symbolCounter_++};
b.initSymbolIterator=function(){b.initSymbol();var a=b.global.Symbol.iterator;a||(a=b.global.Symbol.iterator=b.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&b.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return b.arrayIterator(this)}});b.initSymbolIterator=function(){}};b.arrayIterator=function(a){var c=0;return b.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};b.iteratorPrototype=function(a){b.initSymbolIterator();
a={next:a};a[b.global.Symbol.iterator]=function(){return this};return a};b.makeIterator=function(a){b.initSymbolIterator();var c=a[Symbol.iterator];return c?c.call(a):b.arrayIterator(a)};b.arrayFromIterator=function(a){for(var c,b=[];!(c=a.next()).done;)b.push(c.value);return b};b.arrayFromIterable=function(a){return a instanceof Array?a:b.arrayFromIterator(b.makeIterator(a))};var e={assertTruthyString:function(a,c){if(!c)throw Error("Value for "+a+" is undefined, null or blank.");if("string"!==typeof c&&
!(c instanceof String))throw Error("Value for "+a+" is not a string.");if(""===c.trim())throw Error("Value for "+a+" is empty string.");},assertNotNullObject:function(a,c){if(null==c)throw Error("Value for "+a+" is undefined or null");},assertNumber:function(a,c){if(null==c)throw Error(a+" must not be null or undefined.");if("number"!==typeof c||isNaN(c))throw Error("Value for "+a+" is not a number");},assertNumberBetween:function(a,c,b,d){(0,e.assertNumber)(a,c);if(c<b||c>d)throw Error("Value for "+
a+" is outside the range ["+b+","+d+"]");},assertFunction:function(a,c){if(!c)throw Error(a+" must not be truthy.");},assertPositiveNumber:function(a,c){(0,e.assertNumber)(a,c);if(0>c)throw Error(a+" must be a positive number.");}},g=function(a,c,b,d){this.guid=a;this.method=c;this.version=b;this.args=d};g.isValidSerializedMessage=function(a){return!!a&&void 0!==a.omid_message_guid&&void 0!==a.omid_message_method&&void 0!==a.omid_message_version&&"string"===typeof a.omid_message_guid&&"string"===
typeof a.omid_message_method&&"string"===typeof a.omid_message_version&&(void 0===a.omid_message_args||"string"===typeof a.omid_message_args)};g.deserialize=function(a){return new g(a.omid_message_guid,a.omid_message_method,a.omid_message_version,a.omid_message_args)};g.prototype.serialize=function(){var a={};a=(a.omid_message_guid=this.guid,a.omid_message_method=this.method,a.omid_message_version=this.version,a);void 0!==this.args&&(a.omid_message_args=this.args);return a};var d=function(a){this.to=
a};d.prototype.sendMessage=function(a,c){};d.prototype.handleMessage=function(a,c){if(this.onMessage)this.onMessage(a,c)};d.prototype.generateGuid=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return a="y"===a?(c&3|8).toString(16):c.toString(16)})};d.prototype.serialize=function(a){return JSON.stringify(a)};d.prototype.deserialize=function(a){return JSON.parse(a)};var h={OMID_PRESENT_FRAME_NAME:"omid_v1_present",isOmidPresent:function(a){try{return a.frames?
!!a.frames[h.OMID_PRESENT_FRAME_NAME]:!1}catch(c){return!1}},declareOmidPresence:function(a){a.frames&&a.document&&(h.OMID_PRESENT_FRAME_NAME in a.frames||(null==a.document.body&&h.isMutationObserverAvailable_(a)?h.registerMutationObserver_(a):a.document.write('<iframe style="display:none" '+('id="'+h.OMID_PRESENT_FRAME_NAME+'"')+(' name="'+h.OMID_PRESENT_FRAME_NAME+'">')+"</iframe>")))},isMutationObserverAvailable_:function(a){return"MutationObserver"in a},registerMutationObserver_:function(a){var c=
new MutationObserver(function(b){b.forEach(function(b){"BODY"===b.addedNodes[0].nodeName&&(b=a.document.createElement("iframe"),b.id=h.OMID_PRESENT_FRAME_NAME,b.name=h.OMID_PRESENT_FRAME_NAME,b.style.display="none",a.document.body.appendChild(b),c.disconnect())})});c.observe(a.document.documentElement,{childList:!0})}},r=function(a){this.to=a;this.handleExportedMessage=r.prototype.handleExportedMessage.bind(this)};b.inherits(r,d);r.prototype.sendMessage=function(a,c){c=void 0===c?this.to:c;if(!c)throw Error("Message destination must be defined at construction time or when sending the message.");
c.handleExportedMessage(a.serialize(),this)};r.prototype.handleExportedMessage=function(a,c){g.isValidSerializedMessage(a)&&this.handleMessage(g.deserialize(a),c)};var v={error:function(a){for(var c=[],d=0;d<arguments.length;++d)c[d-0]=arguments[d];p(function(){throw new (Function.prototype.bind.apply(Error,[null].concat(["Could not complete the test successfully - "],b.arrayFromIterable(c))));},function(){return console.error.apply(console,[].concat(b.arrayFromIterable(c)))})},debug:function(a){for(var c=
[],d=0;d<arguments.length;++d)c[d-0]=arguments[d];p(function(){},function(){return console.error.apply(console,[].concat(b.arrayFromIterable(c)))})}},t=eval("this");var k=function(){if("undefined"!==typeof f&&f)return f;if("undefined"!==typeof global&&global)return global;if("undefined"!==typeof window&&window)return window;if("undefined"!==typeof t&&t)return t;throw Error("Could not determine global object context.");}();var u=function(a,c){this.to=c=void 0===c?k:c;var b=this;a.addEventListener("message",
function(a){if("object"===typeof a.data){var c=a.data;g.isValidSerializedMessage(c)&&(c=g.deserialize(c),a.source&&b.handleMessage(c,a.source))}})};b.inherits(u,d);u.isCompatibleContext=function(a){return!!(a&&a.addEventListener&&a.postMessage)};u.prototype.sendMessage=function(a,c){c=void 0===c?this.to:c;if(!c)throw Error("Message destination must be defined at construction time or when sending the message.");c.postMessage(a.serialize(),"*")};var w=function(a,c,b){b=void 0===b?h.isOmidPresent:b;
return(c=m(a,c))?new r(c):a.top&&b(a.top)?new u(a,a.top):null};d=function(a){if(this.communication=void 0===a?(0,w)(k,["omid","v1_VerificationServiceCommunication"]):a)this.communication.onMessage=this.handleMessage_.bind(this);this.remoteIntervals_=this.remoteTimeouts_=0;this.callbackMap_={}};d.prototype.isSupported=function(){return!!this.communication};d.prototype.registerSessionObserver=function(a,c){(0,e.assertFunction)("functionToExecute",a);this.sendMessage_("addSessionListener",a,c)};d.prototype.addEventListener=
function(a,c){(0,e.assertTruthyString)("eventType",a);(0,e.assertFunction)("functionToExecute",c);this.sendMessage_("addEventListener",c,a)};d.prototype.sendUrl=function(a,c,b){(0,e.assertTruthyString)("url",a);this.sendMessage_("sendUrl",function(a){a&&c?c():!a&&b&&b()},a)};d.prototype.injectJavaScriptResource=function(a,c,b){var d=this;(0,e.assertTruthyString)("url",a);k.document?this.injectJavascriptResourceUrlInDom_(a,c,b):this.sendMessage_("injectJavaScriptResource",function(e,q){e?(d.evaluateJavaScript_(q,
a),c()):(v.error("Service failed to load JavaScript resource."),b())},a)};d.prototype.injectJavascriptResourceUrlInDom_=function(a,c,b){var d=k.document,e=d.body;d=d.createElement("script");d.onload=c;d.onerror=b;d.src=a;d.type="application/javascript";e.appendChild(d)};d.prototype.evaluateJavaScript_=function(a,c){try{eval(a)}catch(q){v.error('Error evaluating the JavaScript resource from "'+c+'".')}};d.prototype.setTimeout=function(a,c){(0,e.assertFunction)("functionToExecute",a);(0,e.assertPositiveNumber)("timeInMillis",
c);if(this.hasTimeoutMethods_())return k.setTimeout(a,c);var b=this.remoteTimeouts_++;this.sendMessage_("setTimeout",a,b,c);return b};d.prototype.clearTimeout=function(a){(0,e.assertPositiveNumber)("timeoutId",a);this.hasTimeoutMethods_()?k.clearTimeout(a):this.sendOneWayMessage_("clearTimeout",a)};d.prototype.setInterval=function(a,c){(0,e.assertFunction)("functionToExecute",a);(0,e.assertPositiveNumber)("timeInMillis",c);if(this.hasIntervalMethods_())return k.setInterval(a,c);var b=this.remoteIntervals_++;
this.sendMessage_("setInterval",a,b,c);return b};d.prototype.clearInterval=function(a){(0,e.assertPositiveNumber)("intervalId",a);this.hasIntervalMethods_()?k.clearInterval(a):this.sendOneWayMessage_("clearInterval",a)};d.prototype.hasTimeoutMethods_=function(){return"function"===typeof k.setTimeout&&"function"===typeof k.clearTimeout};d.prototype.hasIntervalMethods_=function(){return"function"===typeof k.setInterval&&"function"===typeof k.clearInterval};d.prototype.handleMessage_=function(a,c){c=
a.method;var b=a.guid;a=a.args;if("response"===c&&this.callbackMap_[b]){var d=a?JSON.parse(a):[];this.callbackMap_[b].apply(this,d)}"error"===c&&window.console&&v.error(a)};d.prototype.sendOneWayMessage_=function(a,c){for(var d=[],e=1;e<arguments.length;++e)d[e-1]=arguments[e];this.sendMessage_.apply(this,[].concat([a,null],b.arrayFromIterable(d)))};d.prototype.sendMessage_=function(a,c,b){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];this.isSupported()&&(e=this.communication.generateGuid(),
c&&(this.callbackMap_[e]=c),d=new g(e,"VerificationService."+a,"1.0.2-dev",JSON.stringify(d)),this.communication.sendMessage(d))};(0,function(a,c,b){if(b=void 0===b?"undefined"===typeof n?null:n:b)a=a.split("."),a.slice(0,a.length-1).reduce(l,b)[a[a.length-1]]=c})("OmidVerificationClient",d)},"undefined"===typeof exports?void 0:exports);
(function(){function f(){var b={location:{protocol:"https:"}};b.parent=b;b.top=b;b.document={getElementById:function(){},createElement:function(){},body:{insertBefore:function(){}},querySelectorAll:function(){return[]}};return b}function n(b){b=b||("http:"!=window.location.protocol?"https:":"http:");return b+"//cdn.doubleverify.com/dv-measurements"+(10>100*Math.random()?200:198)+".js"}function l(){window.$dv=window.parent.$dv;window.$frmId=Math.random().toString(36)+Math.random().toString(36);window.dv_flow=
2}function p(b,g){if(b){var d=document.createElement("script");d.src=b;d.onerror=function(){(new Image).src=g+"scriptLoading"};document.body.appendChild(d)}}dv_flow=2;var m={omidObject:{},isSupported:function(){try{return this.omidObject=new OmidVerificationClient["1.0.2-dev"],this.omidObject.isSupported()}catch(e){return!1}},execute:function(){var b=this.omidObject;$dv={omidJsClient:b,tags:{}};"undefined"==typeof window&&($dv.isDomlessEnvironment=!0,window=f());$frmId=Math.random().toString(36)+
Math.random().toString(36);b.registerSessionObserver(function(e){try{switch(e.type){case "sessionStart":var d=n("https:");$dv.omidSessionData=e;b.injectJavaScriptResource(d);break;case "sessionError":b.sendUrl("https://tps.doubleverify.com/visit.jpg?ctx=818052&cmp=1619415&dvtagver=6.1.src&dvp_isLostImp=1&dvp_omid=1&dvp_jsErrMsg=omidSession"+(e.data&&e.data.message||""))}}catch(h){b.sendUrl("https://tps.doubleverify.com/visit.jpg?ctx=818052&cmp=1619415&dvtagver=6.1.src&dvp_isLostImp=1&dvp_omid=1&dvp_jsErrMsg=omidCallback"+
h.message)}},"DV")}},b={execute:function(){try{window.$dv=window.$dv||{tags:{}};var b=n("https:"),g=Math.floor(1E12*(Math.random()+"")),d=document.createElement("iframe");d.name=d.id="iframe_"+g;d.setAttribute("data-dv-frm",g);d.width="0";d.height="0";d.style.display="none";d.src="about:blank";if(document.currentScript)document.currentScript.parentNode.insertBefore(d,document.currentScript);else if(document.body)document.body.insertBefore(d,document.body.firstChild);else{var h=document.getElementsByTagName("head")[0];
h.insertBefore(d,h.firstChild)}var f=d&&(d.contentDocument||d.contentWindow&&d.contentWindow.document||frames&&frames[d.name]&&frames[d.name].document),m='<html><head><script type="text/javascript">('+l.toString()+')();\x3c/script></head><body><script type="text/javascript">('+p.toString()+')("'+b+'", "https://tps.doubleverify.com/visit.jpg?ctx=818052&cmp=1619415&dvtagver=6.1.src&dvp_isLostImp=1&dvp_jsErrMsg=");\x3c/script></body></html>';if(f)f.open(),f.write(m),f.close();else{var t=encodeURIComponent(m.replace(/'/g,
"\\'").replace(/\n|\r\n|\r/g,""));d.src='javascript: (function(){document.open();document.domain="'+window.document.domain+"\";document.write('"+t+"');})()"}}catch(k){(new Image).src="https://tps.doubleverify.com/visit.jpg?ctx=818052&cmp=1619415&dvtagver=6.1.src&dvp_isLostImp=1&dvp_jsErrMsg=visitLoading"+k.message}}};try{m.isSupported()?m.execute():b.execute()}catch(e){}})();
